### ISSUE TITLE
Online Time Series Regression 

### ISSUE THREAD

**Issue by puzzlecollector** [alison-carrera/onn#11]
@alison-carrera 
Would it be possible to extend the hedge backpropagation to stacked LSTM structure? I am interested in doing online time series prediction, so for example at time t, the model gets length 10 sequence at times [t-9,t-8,...,t-1,t] and predicts the value at time t+1. Would you say such task is possible using ONN?

**Comment by alison-carrera** [comment]
Hi @puzzlecollector, nice question :D

It's theoretically possible, if a backpropagation works on an ANN it will work on LSTM as well, but I stay wondering whether it is possible to converge. We know LSTM is a very unstable network and keeps exploding gradients sometimes. Either the online update can cause a lot of gradient explosion or the network will not converge because there are more parameters to be learned. I think you can try this approach, I'm certainly the algorithm will work without executions errors, my only precaution is about convergence. Will it converge? We need to try.

**Comment by puzzlecollector** [comment]
@alison-carrera thanks for the reply! Yes I guess I wouldn't know until I try. I'll let you know if I get anywhere with my experiments. Thanks :)
